### ISSUE TITLE
Can you release the binary EXE

### ISSUE THREAD

**Issue by peter8777555** [ytk2128/dll-merger#1]
1. Can you release the binary EXE  ?
2. Can it merge multi DLLs ?
3. Can it support X64 DLL ?

**Comment by Stoutscientist** [comment]
Might be a little late, but here it is: https://www.mediafire.com/file/p8ktytde0fm1kap/merger.exe/file

**Comment by peter8777555** [comment]
> Might be a little late, but here it is: https://www.mediafire.com/file/p8ktytde0fm1kap/merger.exe/file

Hi ! Stoutscientist :

Thank you a lot.

I have tested Networx 5.5.5 portable(Freeware).

C:\Test>Merger.exe NetWorx.exe sqlite.dll
DLLs are successfully merged.

If i rename sqlite.dll to T_sqlite.dll

Run NetWorx.exe_out.exe

Error:

NetWorx.exe_out.exe - System Error

The code execution cannot proceed because sqlite.dll was not found. 
Reinstalling the program may fix this problem.

**Comment by Stoutscientist** [comment]
Honestly, I don't know much about the program, I downloaded it the day I sent it so I probably won't be much of a help lol

**Comment by peter8777555** [comment]
> Honestly, I don't know much about the program, I downloaded it the day I sent it so I probably won't be much of a help lol

OK.
Thank you.

**Comment by Stoutscientist** [comment]
> > Honestly, I don't know much about the program, I downloaded it the day I sent it so I probably won't be much of a help lol
> 
> OK.
> Thank you.

No problem! Sorry I can't help more.

**Comment by Thyristor-Chopper** [comment]
> Might be a little late, but here it is: https://www.mediafire.com/file/p8ktytde0fm1kap/merger.exe/file

link is broken
