### ISSUE TITLE
merge multiple dlls in one?

### ISSUE THREAD

**Issue by subabrain** [ytk2128/dll-merger#2]
Hi,

is it possible to merge multiple dlls into one dll?

and if yes - does it also work for 64 bit assemblies?

Would be great!

Thanks a lot!

**Comment by ytk2128** [comment]
Hi,

It is totally possible because dlls are also PE file!

**Comment by subabrain** [comment]
Hi,

ah ok great!

your application is very good!

but one question - can i use 64 bit dlls as well?

Thanks and Greetings!
Robert

**Comment by ytk2128** [comment]
Hi,

It only supports PE32 which is x32 executables!

**Comment by subabrain** [comment]
hi,

ok - i see - thanks a lot!

Greets
Robert
